### ISSUE TITLE
Get your public ip with :ip

### ISSUE THREAD

**Issue by profy12** [federico-terzi/espanso#103]
My first package, tested only on Linux.

https://github.com/profy12/espanso-package-ip

**Comment by federico-terzi** [comment]
Hi @profy12,
Thank you for your submission, it's surely helpful. There are just a couple of edits I'd like you to do before publishing. In the `ip` [README](https://github.com/profy12/espanso-package-ip/blob/master/ip/README.md):

* Please add `( Linux only )` at the end of the `package_desc`
* And add a short message in the body, explaining that is linux only and have only be tested on that system.

I'm asking you to add those edits because I can imagine a Windows/MacOS user getting disappointed if something is not working.

Thanks

**Comment by profy12** [comment]
Ok it's done.

**Comment by federico-terzi** [comment]
All right! here's your package: https://hub.espanso.org/packages/espanso-package-ip/

Thanks for your help
