### ISSUE TITLE
Use hotkey combinations?

### ISSUE THREAD

**Issue by DutchPete** [federico-terzi/espanso#107]
Is it possible to use e.g. <kbd>CTRL</kbd> + <kbd>Shift</kbd> + e as a trigger for e.g. é?
If yes, what is the correct syntax for it?

**Comment by federico-terzi** [comment]
Hi @DutchPete,

Thank you for your feedback. At the moment it's not currently possible, but we can discuss to add it to the roadmap.

The main problem with this feature is that espanso is not able to "block" shortcuts, only detect them. This has an unwanted consequence: if you define a match for the shortcut "CTRL+SHIFT+e" and the current application you are using already defined that shortcut for an action, at the moment you trigger the match you will execute the action as well.
In order to minimize the problem, you could choose complex shortcuts to minimize the chance of conflicts ( like "CTRL+ALT+SHIFT+e" ), but I think it could be inconvenient.

Let me know what you think

**Comment by DutchPete** [comment]
Hello @federico-terzi : Thanks for your explanation.
You are right, this happens with other apps that allow hotkeys for different purposes. I used to keep a list with all my hotkeys, but it becomes cumbersome, and one forgets to amend the list.

So, I think it is not necessary to add it to the roadmap.
