### ISSUE TITLE
Clipboard gets overwritten

### ISSUE THREAD

**Issue by JohnFinn** [federico-terzi/espanso#174]
Why clipboard is getting overwritten, is it some kind of workaround? If using of clipboard is absolutely necessary, wouldn't it be better to preserve clipboard content?

**Comment by federico-terzi** [comment]
Hey @JohnFinn,
Sorry for the inconvenience, at the moment espanso on linux is more stable when using the clipboard backend instead of directly injecting keystrokes. 
To overcome your problem, please add the following line to your `default.yml` file:

```yaml
preserve_clipboard: true
```

Please note that only `text` based clipboard will be preserved and not images.

In the next release of espanso, it will be enabled by default.

Cheers

**Comment by JohnFinn** [comment]
By the way, how direct keystroke injection is done? Before I have found out about espanso, I've written a [project](https://github.com/JohnFinn/str2ev), that does keyboard injection in linux.
Where is the place in the code, which does it? I'd like to play with it and hopefully make it stable.

**Comment by federico-terzi** [comment]
Currently espanso supports two different input modes (called backends):
* `Clipboard` (the default one)
* `Inject`

You could switch to the Inject one by adding this row in the `default.yml` file:

```yaml
backend: Inject
```
Espanso doesn't directly implement the injection mechanism, and instead uses `libxdo`, the one that powers `xdotool`.
The problems with this library is that it is relatively slow for medium texts and doesn't correcly support unicode characters in many applications (all the ones built with QT, such as Telegram).

If you want to experiment a little, here's the place in which the library is called https://github.com/federico-terzi/espanso/blob/505c3db6905c4c6b89bf0b0943664027d45bfcb5/native/liblinuxbridge/bridge.cpp#L272

Cheers

**Comment by owzim** [comment]
> To overcome your problem, please add the following line to your default.yml file:
> `preserve_clipboard: true`

This does not work for me, then all expansion result in empty strings, I also restarted respanso

Any suggestions?

**Comment by federico-terzi** [comment]
Hey @owzim,

I'm sorry you experienced these issues, let me ask you a few questions so that I can help you:

* Could you please give me a bit more details about your setup (OS and version of espanso)?
* Which install method did you choose?
* Could you please post the output of `espanso log` here?
* Does all expansions result in empty strings only with `preserve_clipboard: true` or also when it is disabled?

Cheers :)

**Comment by federico-terzi** [comment]
Hey guys,
I'm closing the issue as version 0.5.2 shipped with the `Auto` backend (more information on the Releases page) that should partially solve the problem.

Cheers
