### ISSUE TITLE
Espanso under Wayland on KDE Neon not starting

### ISSUE THREAD

**Issue by pnunn** [federico-terzi/espanso#1842]
I just switched from X11 to Wayland, and have tried installing espanso from the Wayland deb file after removing the X11 version.

It seems to install OK, but when I run it, espanso seems to think I'm still running under X and pops up the dialog to say I'm running the wrong version and then shuts down.

I'm running espanso 2.2.1 from the espanso-debian-wayland-amd64.deb package.

Just rebooted and it sort of works... I get a crashed application in my task bar, but the expansions work until I shut down that crashed app. However, when I try and do espanso start again it throws up the dialog saying This version was compiled for Wayland-based systems, but you seem to be on X11-based desktop, but I'm not.

**To Reproduce**
1.  Install the deb.
2. Try and run esponso from the terminal

If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem

10:52:09 [daemon(3774)] [INFO] reading configs from: "/home/pnunn/.config/espanso"
10:52:09 [daemon(3774)] [INFO] reading packages from: "/home/pnunn/.config/espanso/match/packages"
10:52:09 [daemon(3774)] [INFO] using runtime dir: "/home/pnunn/.cache/espanso"
10:52:09 [daemon(3774)] [INFO] system info: KDE neon v22.04 - kernel: 6.5.0-17-generic
10:52:09 [daemon(3774)] [WARN] keyboard layout watcher couldn't determine active layout.
10:52:09 [daemon(3774)] [INFO] watching for changes in path: "/home/pnunn/.config/espanso"
10:52:09 [daemon(3774)] [INFO] espanso version: 2.2.1
10:52:09 [daemon(3774)] [INFO] spawning the worker process...
10:52:09 [daemon(3774)] [INFO] binded to IPC unix socket: /home/pnunn/.cache/espanso/espansodaemonv2.sock
10:52:09 [worker(3780)] [INFO] reading configs from: "/home/pnunn/.config/espanso"
10:52:09 [worker(3780)] [INFO] reading packages from: "/home/pnunn/.config/espanso/match/packages"
10:52:09 [worker(3780)] [INFO] using runtime dir: "/home/pnunn/.cache/espanso"
10:52:09 [worker(3780)] [INFO] system info: KDE neon v22.04 - kernel: 6.5.0-17-generic
10:52:09 [worker(3780)] [INFO] binded to IPC unix socket: /home/pnunn/.cache/espanso/espansoworkerv2.sock
10:52:09 [worker(3780)] [INFO] using WaylandAppInfoProvider
10:52:09 [worker(3780)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
10:52:09 [worker(3780)] [INFO] monitoring the status of the daemon process
10:52:09 [worker(3780)] [INFO] using EVDEVSource
10:52:09 [worker(3780)] [INFO] Querying modifier status...
10:52:10 [worker(3780)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
10:52:10 [worker(3780)] [INFO] using EVDEVInjector
10:52:10 [worker(3780)] [INFO] using WaylandFallbackClipboard
10:52:12 [worker(3780)] [ERROR] Unable to show notification: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
10:53:05 [daemon(3774)] [ERROR] received unexpected exit code from worker 90, exiting
10:53:32 [service(7562)] [INFO] reading configs from: "/home/pnunn/.config/espanso"
10:53:32 [service(7562)] [INFO] reading packages from: "/home/pnunn/.config/espanso/match/packages"
10:53:32 [service(7562)] [INFO] using runtime dir: "/home/pnunn/.cache/espanso"
10:53:32 [service(7562)] [INFO] system info: KDE neon v22.04 - kernel: 6.5.0-17-generic
10:53:37 [service(7562)] [ERROR] unable to start service: timed out
10:53:37 [service(7562)] [ERROR] Hint: sometimes this happens because another Espanso process is left running for some reason.
10:53:37 [service(7562)] [ERROR]       Please try running 'espanso restart' or manually killing all Espanso processes, then try again.
10:59:17 [service(18589)] [INFO] reading configs from: "/home/pnunn/.config/espanso"
10:59:17 [service(18589)] [INFO] reading packages from: "/home/pnunn/.config/espanso/match/packages"
10:59:17 [service(18589)] [INFO] using runtime dir: "/home/pnunn/.cache/espanso"
10:59:17 [service(18589)] [INFO] system info: KDE neon v22.04 - kernel: 6.5.0-17-generic
10:59:22 [service(18589)] [ERROR] unable to start service: timed out
10:59:22 [service(18589)] [ERROR] Hint: sometimes this happens because another Espanso process is left running for some reason.
10:59:22 [service(18589)] [ERROR]       Please try running 'espanso restart' or manually killing all Espanso processes, then try again.

**Setup information**
- OS: What OS are you using?
KDE Neon.
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)
2.2.1

**Comment by pnunn** [comment]
Some more context... echo $XDG_SESSION_TYPE does return wayland.

**Comment by morgan-dgk** [comment]
Hmmm, this is strange. What does the output of `loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type` show? This is the command use to determine what session type is used.

**Comment by pnunn** [comment]
I tried to grab a screen shot of the stuck process in the task bar after starting into wayland but it wouldn't capture it for me.  There is a 'W' in a circle and when you hover over it you get a box  Espanso sync tool not responding which some times is half red and half yellow if that helps any.

loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type
Type=wayland

Type=x11

Interesting that there are two perhaps??

**Comment by morgan-dgk** [comment]
The unresponsive window is a separate issue #1776. From the output above it looks like there are two sessions associated with your EUID, one for wayland and one for x11. This explains the message you see when trying to restart espanso.

**Comment by pnunn** [comment]
OK. How? This is a bulk standard KDE Neon install. Could it be the layer allowing x11 apps to run on wayland? Any fixes?

**Comment by morgan-dgk** [comment]
I'm not familiar with KDE, but I don't believe xwayland requires a separate X11 session (it doesn't on my system). 

Currently, the [code](https://github.com/espanso/espanso/blob/03c39196c354580c27035c799186af17df49ca17/espanso/src/cli/launcher/edition_check.rs#L57) used to determine session type uses the value from the last session listed where there are multiple sessions for the current user.

Are you signing into both Wayland and X11 via the KDE display manager?

**Comment by pnunn** [comment]
Not that I'm aware of. I'm using a Wayland Plasma session at logon from the logon window.  Not sure how you could use both, but guess its possible.

**Comment by pnunn** [comment]
Some times it works! I logged in yesterday and espanso worked fine. Today after a reboot.. nope. Must be an order thing I guess, but no clue what.

**Comment by pnunn** [comment]
I just upgraded Neon to the KDE6 release and unfortunately have exactly the same situation. The test for the DM seems to return both X11 and Wayland so it won't start on Wayland (does work on X11).

**Comment by morgan-dgk** [comment]
Hey @pnunn, thinking out loud here. Is it possible the display manager / login starts and uses an X11 session which is not being terminated on login? If so, have you tried terminating this session after logging in to the Wayland session?

**Comment by pnunn** [comment]
Hi @morgan-dgk thanks for this. It is certainly possible and if I had any clue how to find the session and kill it I'd be more than happy to give it a go. Any pointers?

Could it also be something to do with the X-Wayland layer?

**Comment by morgan-dgk** [comment]
> Hi @morgan-dgk thanks for this. It is certainly possible and if I had any clue how to find the session and kill it I'd be more than happy to give it a go. Any pointers?
> 
> Could it also be something to do with the X-Wayland layer?

Try `who -u` to list all users sessions with pid and the do `sudo kill -9 <PID for x11 session>`. 

I'm not sure on your question re X-Wayland. On my compositor the xwayland does not appear to require an active x11 session.

**Comment by morgan-dgk** [comment]
Any update on this @pnunn?

**Comment by pnunn** [comment]
Hi @morgan-dgk I did have one shot at it but must have killed the wrong session and crashed the entire computer (took a bit to get it back to be honest). Will have another look later today (maybe on another machine) and see what happens. I'll let you know.

**Comment by pnunn** [comment]
Hi @morgan-dgk I've been playing with this again, and the only session I can see any mention of Xorg on is the active one.

`ps -aux | grep xorg
root        1710  0.2  0.2 2814612 82240 tty2    Ssl+ 10:44   0:00 /usr/lib/xorg/Xorg -nolisten tcp -background none -seat seat0 vt2 -auth /run/sddm/xauth_fiHdYu -noreset -displayfd 16
pnunn       6111  0.0  0.0   6616  2560 pts/1    S+   10:46   0:00 grep --color=auto xorg
`
and if I kill tty2 I kill my active session and have to reboot.

Is there a way to force espanso to not check for the X session?

**Comment by morgan-dgk** [comment]
Not as far as I am aware. Based on some quick reading, it seems like you may need to configure sddm to use Wayland as the compositor for the greeter (otherwise it will start an x11 session).

This [article](https://wiki.archlinux.org/title/SDDM#Running_under_Wayland) from the arch wiki should help.

**Comment by pnunn** [comment]
We seem to be making progress (no idea if it will persist yet). I followed your link and found that there was no sddm.conf.d directory, however, I did do the apply plasma settings bit mentioned in the header of the article, and after issuing the setcap command and restarting espanso, it seems to be running.

I'll try a reboot shortly and see if its still working then or if this is a total fluke.

**Comment by pnunn** [comment]
OK. After a reboot... espanso seems to start OK, and I can see it running, find the version and it pretty much seems right, EXCEPT, it does nothing!!

None of the expansions work. I re-did the setcap command, restarted espanso and still nothing is picked up.

The logs have the following

`27 Mar 14 20:49:13 peter-xps157590 espanso[6723]: 20:49:13 [worker(6723)] #033[0m#033[34m[INFO] #033[0mexiting worker process and daemon...
   26 Mar 14 20:49:14 peter-xps157590 espanso[6717]: 20:49:14 [daemon(6717)] #033[0m#033[34m[INFO] #033[0mworker requested a general exit, quitting the daemon
   24 Mar 14 20:49:16 peter-xps157590 systemd[2514]: Started espanso.
   23 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0mreading configs from: "/home/pnunn/.config/espanso"
   22 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0mreading packages from: "/home/pnunn/.config/espanso/match/packages"
   21 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0musing runtime dir: "/home/pnunn/.cache/espanso"
   20 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0msystem info: KDE neon v22.04 - kernel: 6.5.0-25-generic
   19 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[33m[WARN] #033[0mkeyboard layout watcher couldn't determine active layout.
   18 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0mwatching for changes in path: "/home/pnunn/.config/espanso"
   17 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0mespanso version: 2.2.1
   16 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0mspawning the worker process...
   15 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0mbinded to IPC unix socket: /home/pnunn/.cache/espanso/espansodaemonv2.sock
   14 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0mreading configs from: "/home/pnunn/.config/espanso"
   13 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0mreading packages from: "/home/pnunn/.config/espanso/match/packages"
   12 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0musing runtime dir: "/home/pnunn/.cache/espanso"
   11 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0msystem info: KDE neon v22.04 - kernel: 6.5.0-25-generic
   10 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0mbinded to IPC unix socket: /home/pnunn/.cache/espanso/espansoworkerv2.sock
    9 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0musing WaylandAppInfoProvider
    8 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[33m[WARN] #033[0munable to determine keyboard layout automatically, please explicitly specify it in the configuration.
    7 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0mmonitoring the status of the daemon process
    6 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0musing EVDEVSource
    5 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0mQuerying modifier status...
    4 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[33m[WARN] #033[0munable to determine keyboard layout automatically, please explicitly specify it in the configuration.
    3 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0musing EVDEVInjector
    2 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0musing WaylandFallbackClipboard
    1 Mar 14 20:49:16 peter-xps157590 kernel: [  283.247330] input: Espanso virtual device as /devices/virtual/input/input24
`
I'm not sure if that's of any help at all.

**Comment by morgan-dgk** [comment]
Can you try specifying your keyboard Layout in your config file?

It should look something like
```
keyboard_layout:
layout: us
variant: your-variant-if-any
```

-------- Message d'origine --------
Le 14 mars 2024, 05:52, Peter Nunn < ***@***.***> a écrit :
OK. After a reboot... espanso seems to start OK, and I can see it running, find the version and it pretty much seems right, EXCEPT, it does nothing!!
None of the expansions work. I re-did the setcap command, restarted espanso and still nothing is picked up.
The logs have the following
27 Mar 14 20:49:13 peter-xps157590 espanso[6723]: 20:49:13 [worker(6723)] #033[0m#033[34m[INFO] #033[0mexiting worker process and daemon... 26 Mar 14 20:49:14 peter-xps157590 espanso[6717]: 20:49:14 [daemon(6717)] #033[0m#033[34m[INFO] #033[0mworker requested a general exit, quitting the daemon 25 Mar 14 20:49:14 peter-xps157590 tailscaled[1733]: open-conn-track: timeout opening (TCP 100.102.215.11:53874 => 85.10.198.55:80); no associated peer node 24 Mar 14 20:49:16 peter-xps157590 systemd[2514]: Started espanso. 23 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0mreading configs from: "/home/pnunn/.config/espanso" 22 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0mreading packages from: "/home/pnunn/.config/espanso/match/packages" 21 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0musing runtime dir: "/home/pnunn/.cache/espanso" 20 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0msystem info: KDE neon v22.04 - kernel: 6.5.0-25-generic 19 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[33m[WARN] #033[0mkeyboard layout watcher couldn't determine active layout. 18 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0mwatching for changes in path: "/home/pnunn/.config/espanso" 17 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0mespanso version: 2.2.1 16 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0mspawning the worker process... 15 Mar 14 20:49:16 peter-xps157590 espanso[7860]: 20:49:16 [daemon(7860)] #033[0m#033[34m[INFO] #033[0mbinded to IPC unix socket: /home/pnunn/.cache/espanso/espansodaemonv2.sock 14 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0mreading configs from: "/home/pnunn/.config/espanso" 13 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0mreading packages from: "/home/pnunn/.config/espanso/match/packages" 12 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0musing runtime dir: "/home/pnunn/.cache/espanso" 11 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0msystem info: KDE neon v22.04 - kernel: 6.5.0-25-generic 10 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0mbinded to IPC unix socket: /home/pnunn/.cache/espanso/espansoworkerv2.sock 9 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0musing WaylandAppInfoProvider 8 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[33m[WARN] #033[0munable to determine keyboard layout automatically, please explicitly specify it in the configuration. 7 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0mmonitoring the status of the daemon process 6 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0musing EVDEVSource 5 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0mQuerying modifier status... 4 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[33m[WARN] #033[0munable to determine keyboard layout automatically, please explicitly specify it in the configuration. 3 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0musing EVDEVInjector 2 Mar 14 20:49:16 peter-xps157590 espanso[7866]: 20:49:16 [worker(7866)] #033[0m#033[34m[INFO] #033[0musing WaylandFallbackClipboard 1 Mar 14 20:49:16 peter-xps157590 kernel: [ 283.247330] input: Espanso virtual device as /devices/virtual/input/input24
I'm not sure if that's of any help at all.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.￼Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/espanso/espanso/issues/1842#issuecomment-1997054611">https://github.com/espanso/espanso/issues/1842#issuecomment-1997054611", "url": "[https://github.com](<a href=)/espanso/espanso/issues/1842#issuecomment-1997054611">https://github.com/espanso/espanso/issues/1842#issuecomment-1997054611", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by pnunn** [comment]
OK. That works!! The only problem for me is that I switch layouts :(. I use dvorak and switch to the dvorak layout when I use my laptop keyboard, but my main keyboard is already set to dvorak and uses US as the default layout for the system as it does the conversion for me. 

Minor issue in practice. If I have to change the config each time, so be it, but would be nice if it worked :)

Thanks for the help to this point though. It's great to have it working again!!

**Comment by morgan-dgk** [comment]
Yeah, wayland provides a mechanism for managing keyboard layout on a per window basis but we're not currently handling this. Would be a good future enhancement!

**Comment by morgan-dgk** [comment]
@AucaCoyan should be good to close

**Comment by AucaCoyan** [comment]
Thank you! One less issue to think about
