### ISSUE TITLE
Still problems with German Umlaute in Thunderbird

### ISSUE THREAD

**Issue by matthias-rudnick** [federico-terzi/espanso#1845]
I use espanso on Tuxedo, an Ubuntu based distribution.

espanso works fine, except in Thunderbird. I know the problem is not new, but the available suggestions didn't solve the problem for me.

This is my match:

- trigger: ":vgm"
    replace: "Viele Grüße,\nMatthias"

When I am using the 
backend:  Auto or 
backend: Clipboard 
espanso pastes the Clipboard.

When I am using 
backend: Inject
I get:

:Viele Grße,

Matthias

The colon is there and the ü is missing.
Adding the file thunderbird.yml didn't fix my problem either.

**Comment by smeech** [comment]
In case it's any help, my `thunderbird.yml` is:
```
name: Thunderbird

filter_class: "[Tt]hunderbird"
backend: Clipboard
x11_use_xclip_backend: true
```
Nevertheless, I still have some problems. With or without it, the ü comes out correctly here, however, (Mint Xfce, Thunderbird 115.6.0), although in an HTML message the `\n` doesn't work. 

You could try [`force_mode: keys`](https://espanso.org/docs/matches/basics/#injection-mechanism) in the trigger, in case backend: Inject is worth using in your `thunderbird.yml`, although, as you can see, `Clipboard` generally works better for me.

**Comment by matthias-rudnick** [comment]
Thanks for your help. 
I have experienced the same problems as you do, the \n is not working, I get
Viele Grüße, Matthias Rudnick

If I use:
 - trigger: ":vgr"
    replace: "Viele Grüße,\nMatthias Rudnick"
    force_mode: keys

I get a bad bahivour again.
 
:Viele Grße,

Matthias Rudnick

**Comment by smeech** [comment]
markdown: and html: appear to work better in an HTML compose window, but both give Chinese characters in a plain text compose window! E.g.:
```
  - trigger: ":vgm"
    markdown: |
      Viele Grüße,

      Matthias
```
I suppose one could have separate triggers for each type of compose window. Unfortunately, the Active Application Information (#detect#) is the same for each so there's no chance of filtering them automatically. 

I've even tried assigning an intermediate `echo:` variable, which can occasionally make a difference, without success.

There's a long discussion at #455, with links to related issues.

If you routinely only use HTML, then we have a solution. Otherwise, just use a Thunderbird signature!

**Comment by matthias-rudnick** [comment]
Thank you very much for your help. 
Your suggestions finally resolved my problems in Thunderbird.
