### ISSUE TITLE
Issue with Deleting Text After Inserting a Snippet

### ISSUE THREAD

**Issue by andygitarre** [federico-terzi/espanso#1876]
Hello Espanso Team,

I am encountering an issue with Espanso on my system where, after inserting a snippet, the entire text gets deleted if I press the backspace key to remove just one character. This behavior occurs every time I use a snippet, rendering me unable to effectively use Espanso for my tasks.

Steps to Reproduce:
Trigger a snippet by typing its associated trigger phrase.
After the snippet text is inserted, I press the backspace key to remove a character.
Instead of removing just the intended character, the entire text of the snippet is deleted.

Expected Behavior:
I expect that only the character I am trying to delete would be removed, not the entire snippet text.

Actual Behavior:
The entire snippet text is deleted upon pressing the backspace key after inserting a snippet.

System Information:

Operating System: macOS 14.3.1
Espanso Version: 14.3.1

I would appreciate any assistance or suggestions to resolve this issue. Thank you in advance for your help.

**Comment by smeech** [comment]
The backspace method is intentional, to revert expansions triggered where you don't want them. If you need to remove a character, then type a space or something and then remove two. Alternatively, turn off [`undo_backspace:`](https://espanso.org/docs/configuration/options/#options-reference), but this will turn it off globally.
Otherwise amend your `trigger:`/`replace:` pairs so you don't need to remove a character. There are various ways in which this might be done flexibly (e.g. `regex:` triggers), but we'd need to see the code you're using.

**Comment by andygitarre** [comment]
Thank you for helping me!!

**Comment by smeech** [comment]
You're welcome. Let me know if you need further help. You'll find us on Discord and Reddit.
