### ISSUE TITLE
Formatting of rich text output in gmail

### ISSUE THREAD

**Issue by sb2nov** [federico-terzi/espanso#1926]
Hi, I'm trying to replace some markdown text inside the gmail compose window.

- When I use a simple replace - it pasts in the font and size that is the default for gmail.
- When I use markdown or HTML - the text is a different font and size so I need to fix that every time
- I need to use markdown as I have a few links I am trying to add in the email template

Any ideas on how to fix this?

**Comment by smeech** [comment]
Ongoing discussion on [Reddit](https://www.reddit.com/r/espanso/comments/1bsgesp/formatting_of_markdown_output_in_gmail/).

**Comment by smeech** [comment]
My final comment (for future reference):

That's why I suggest you try the `html:` method. I don't understand why your Gmail Compose injected text is a different size from that typed. It's not something I see here, so it's difficult for me to experiment to find a solution.

With `html:` you can adjust the size of the text using \<font size="+num"> or \<font size="-num">, or \<font size="num"> to specify an absolute font size, e.g:

      - trigger: :test1
        html: '<font size="+2">This is a test for <a href="https://www.google.com">a link</a></font>'

You can even use a block scalar to make it more readable, and add other items:

      - trigger: :test1
        html: |
          <font size="+2">
          This is a test for <a href="https://www.google.com">a link </a>
          </font>

It might be a good idea to check your Gmail settings - Settings, See all settings, General, Default text style:, in case that gives you a clue as to why you're not getting the result you expect.
