### ISSUE TITLE
Accessibility Duplicates

### ISSUE THREAD

**Issue by johnrichardrinehart** [federico-terzi/espanso#208]
Each version/installation of `espanso` triggers a request to allow `espanso` Accessibility permissions in MacOS. However, these permissions aren't removed upon installation of a new version. So, now I have a few `espanso` permissions entries in the Accessibility menu of my system preferences.

Is it possible to clean up the entries?

<img width="669" alt="Screen Shot 2020-03-19 at 1 37 44 PM" src="https://user-images.githubusercontent.com/6321578/77113521-39b95d80-69e8-11ea-8821-9081555581d4.png">

**Comment by federico-terzi** [comment]
Hey @johnrichardrinehart,

Thanks a lot for the feedback, that is definitely an inconvenience. At first sight, I would say this is due Homebrew, because what it does is installing espanso in a different directory each time (standard Homebrew behaviour) and then creating a symbolic link to the binary. 
It seems like macOS rather than considering the link position (which is always the same), considers the actual espanso path (that changes).

As far as I know, you can delete all the old espanso entries. If for some reason you accidentally delete the current one, just run `espanso register` again and authorize it, and you should be good to go.

That said, I'll think about a way to mitigate the problem.

Let me know if that works for you

Cheers :)

**Comment by johnrichardrinehart** [comment]
@federico-terzi 

You're right, thanks. I understand the problem and the fix. Using the `-` button you can delete a selected entry, as indicated in the screenshot below.

I didn't know that I could remove options using this interface. This is acceptable for me. No problem.

Thanks again.

![image](https://user-images.githubusercontent.com/6321578/77187004-0c74ba00-6a91-11ea-851c-d69e84f5f727.png)

**Comment by swrobel** [comment]
Also hit by this semi-annoying issue. At least espanso automatically prompts to request the permission again after updates, but since they're so frequent (really hard to complain about), this has been happening quite a bit lately. Maybe open an issue w/ Homebrew to see if there's a recommended solution @federico-terzi?

**Comment by federico-terzi** [comment]
@swrobel thank you for the feedback! I don't think we have much room of improvement with the current architecture. That said, I'm planning to convert espanso to an AppBundle in the future, which should also solve this problem :)
