### ISSUE TITLE
 Problem if I past the trigger. 

### ISSUE THREAD

**Issue by swordfish181** [federico-terzi/espanso#2100]
### Description

I have a big problem. If i writte the trigger with keyboard, espanso work great, but if i paste the same trigger from clipboard, espanso don't intercept it.

can someone help me?

### Your environment

- Public source code:
- Environment name and version (e.g., Rust 1.59.0):
- Operating system and version (e.g., Ubuntu 20.04.2 LTS):
- Espanso version (e.g., 2.1.4-beta):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by AucaCoyan** [comment]
Mmm, I think this is not expected to work, espanso doesn't "read" the clipboard, but keypresses on the keyboard.
It can not "see within" the clipboard to see if there is a match or not.

In addition, espanso can track if you made a mistake when typing the trigger, so when you press backspace espanso _also_ presses backspace in the "tacking presses" module.
The only time it resets the tracking is when you press the arrows (because it doesn't know where you are at, you loose it there).

Espanso doesn't monitor the screen or the clipboard, just what you type from the clipboard (and other unlikely events like sending key presses via autohotkey and the like).
