### ISSUE TITLE
Using an espanso trigger expansion alongside a regex expansion does not yield the expected result

### ISSUE THREAD

**Issue by TuTiuTe** [federico-terzi/espanso#2141]
### Description

I'll try to showcase it with a very simple example
Let's say we have:
- trigger: ":hi"
  replace: "world"

- regex: ":foo_(?P<value>.*)\\."
  replace: "hello {{value}}"
  
typing ":foo_:hi" expands to ":foo_world" as expected
but then adding the dot (making the expression ":foo_world.") turns it into ":fhello :hi"

### Expected behavior

with the previous example, the expansion should be "hello world"

### Screenshots

https://github.com/user-attachments/assets/325297b6-3c6e-421c-b465-048c4eb257c6

### Your environment

- Public source code:
- Environment name and version (e.g., Rust 1.59.0):
- Operating system and version (e.g., Ubuntu 20.04.2 LTS): Fedora 41 wayland
- Espanso version (e.g., 2.1.4-beta): 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
> typing ":foo_:hi" expands to ":foo_world" as expected

because the Regex is not triggered at all. It's a simple replacement of `:hi` with `world`, on the end of `:foo_`

The Regex, `  - regex: ":foo_(?P.*)\."` appears invalid: 

1. While saving, Espanso reports a "while parsing a quoted scalar, found unknown escape character at line 30 column 12" error. 
2. If (?P.*) is meant to be a capturing group, it needs a name (perhaps `<value>`?).

Consequently, I can't test it here.

Generally speaking, however, only one Espanso expansion can be active at any time. A Regex trigger won't match text added by Espanso, because it only responds to characters _typed_.

If I "correct" your code to:
```yml
  - regex: :foo_(?P<value>.*)\.
    replace: hello {{value}}
```
then I see what you're reporting, which is what I would expect. 

I think what's happening, and this is difficult to describe, is:

1. `:foo_:hi` typed, generates `:foo_world` as above
2. The period causes the Regex to match
3. It backspaces, but now there are too many characters to remove because it's expecting to delete `:foo_:hi`, not `:foo_world`.
4. Consequently, it fails to remove the beginning of the text, leaving the first two characters (the difference in length between `world` and `:hi` - you can test this by increasing the length of the replacement text in your `:hi` trigger).

Have I managed to explain that sufficiently?

**Comment by TuTiuTe** [comment]
sorry, the markdown ate one of the backslashes, plus the name of the capturing group. The expression I tried to write was
```
- regex: ":foo_(?P<value>.*)\\."
  replace: "hello {{value}}"
```
Your explanation is very clear, it's a shame that espanso has no context of what it is doing
Then this isn't really a bug, more of an enhancement

**Comment by smeech** [comment]
I suspected as much, hence my version above. I find it easier to omit [double-quotes](https://espanso.org/docs/matches/quotes/), especially in Regexes, as it saves the need to escape characters, and I can copy the Regex directly to https://regex101.com/ for testing.

It comes back to the fact that only one Espanso expansion can be active at any time.
