### ISSUE TITLE
Expansions take up to 8 seconds with certain keyboard layouts on linux

### ISSUE THREAD

**Issue by owzim** [federico-terzi/espanso#215]
Hi,

expansions sometimes take up to 8 seconds with a German keyboard layout on Pop!_OS 19.10 with very little (15 chars) multiline text. With an english qwerty layout it's the usual half a second. Any debug info you need from me? `espanso log` isn't too insightful.

**Comment by federico-terzi** [comment]
Hey @owzim,

I'd guess it's due to the underlying libxdo implementation, which is changing the keyboard layout in order to type the German characters and that process could slow thing down a bit.

Could you please post  a reproducible example of this match?

In the meanwhile, you could use the Clipboard backend, which shouldn't suffer from these problems (though as you know it suffers from others).

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
In the last version (0.5.4) I added an option to force a specific match to be applied through the Clipboard. Therefore, you could now keep the Auto backend and then flag the problematic matches as Clipboard only with the `force_clipboard` option:

```yaml
- trigger: "trigger"
  replace: "replace"
  force_clipboard: true
```

Cheers :)

**Comment by federico-terzi** [comment]
Hey @owzim,

Could you please try the latest version (0.5.5) turning on Fast Inject?
You can find all the information here: [https://github.com/federico-terzi/espanso/releases/tag/v0.5.5](https://github.com/federico-terzi/espanso/releases/tag/v0.5.5).

Make sure you setup your backend to be Auto

let me know if that helps.

**Comment by owzim** [comment]
@federico-terzi thanks a lot. I am currently primarily on mac, so I will try that at a later time. If you want you can close the issue to keep an overview. I'll reopen if necessary.

**Comment by federico-terzi** [comment]
No problem, let me know if you have other problems :)
