### ISSUE TITLE
[Windows] Crash on Start

### ISSUE THREAD

**Issue by smaragdus** [federico-terzi/espanso#220]
When I start [espanso](https://espanso.org/) version [0.5.4](https://github.com/federico-terzi/espanso/releases/tag/v0.5.4) I get the following error message:

`The procedure entry point SetThreadDpiAwarenessContext could not be located in the dynamic link library C:\Portable Programs\espanso\espanso.exe.`

**screen:**

![espanso 0 5 4 - 2020-04-04 - error - 001](https://user-images.githubusercontent.com/9025757/78424063-9c128f00-7673-11ea-9d02-9153c8b6ff1b.png)

and the program crashes:

**screen:**

![espanso 0 5 4 - 2020-04-04 - error - 002](https://user-images.githubusercontent.com/9025757/78424083-b9475d80-7673-11ea-9e41-40cdcb6b297a.png)

This happens under Windows 8 x64.

Is there any Windows version that works under Windows 8?

**Comment by federico-terzi** [comment]
Hey @smaragdus,

I'm sorry you experienced this issue. Unfortunately, espanso is only supported on Windows 10 (and it always has been). This is due to a number of incompatibilities in Windows 8, that I wasn't able to solve.

I would really like to make espanso available to everyone, but as of now, I don't have the means to support also Windows 8. I hope you will understand :)

Cheers

**Comment by smaragdus** [comment]
@federico-terzi 

I understand but I am a bit surprised since programs which work under Windows 10 usually work under Windows 8 as well.

**Comment by federico-terzi** [comment]
I was surprised as well when I initially experimented on Windows 8, and after a few hours of testing I gave up! In fact there were a couple of people that tried adding support for older versions of Windows, but considering I didn't hear anything back, I assume they didn't find it either :)
