### ISSUE TITLE
Partially replacements of trigger

### ISSUE THREAD

**Issue by Adspectus** [federico-terzi/espanso#248]
Similar to #150 I have the same effect in Ubuntu 18.04. However, the effect only appears in browser (Forefox 75) windows, like this formular window. Now, I am just typing the trigger `:espanso` several times:
```
:esHi there!
:eHi there!
:Hi there!
:Hi there!
:Hi there!
```
As you can see, most of the time the expansion leaves the first character, but sometimes even two or three. Sometimes, the expansion is correct though.

I tried to deinstall and reinstall (with a different method) but the behavior is still the same.

**Comment by federico-terzi** [comment]
Hey @Adspectus,

I'm sorry you experienced this issue. A couple of questions before hand:
* Which version of espanso are you running?
* Could you post the output of `espanso log` here?

Cheers :)

**Comment by Adspectus** [comment]
My version is 0.5.5
```
09:44:37 [ INFO] espanso version 0.5.5
09:44:37 [ INFO] using config path: /home/uwe/.config/espanso
09:44:37 [ INFO] using package path: /home/uwe/.local/share/espanso/packages
09:44:37 [ INFO] starting daemon...
09:44:37 [ INFO] Binded to IPC unix socket: /home/uwe/.local/share/espanso/espanso.sock
09:44:37 [ INFO] espanso is running!
```

**Comment by federico-terzi** [comment]
All right @Adspectus, could you please try to add the following line in your `default.yml` file?

```yaml
fast_inject: true
```

And then restart espanso. Let me know if that helps

**Comment by Adspectus** [comment]
Trying now:
```
:Hi ther!
:Hi there!
Hi there!
:Hi there!
:Hi there!
Hi there!
```

**Comment by federico-terzi** [comment]
Thank you @Adspectus, it seems like espanso is not playing well with Firefox. I'll make some tests myself to see if I can improve the situation. I'll let you know if I find something!

**Comment by federico-terzi** [comment]
Hey @Adspectus,
I've looked into the problem and implemented a fix which hopefully should solve the situation. In particular, it seems like firefox is not able to catch up with those events fast enough, so the fix is basically to tell espanso to "slow down" when using Firefox.

The fix will be shipped in the next release, coming in the upcoming days.
When it will be released, you should update espanso and add a file named `firefox.yml` in the `user/` folder with the following content:

```yaml
filter_class: "Firefox"
backspace_delay: 10
inject_delay: 10
```

You can also play with those two values, (higher values = slower typing but more reliable).

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
espanso version 0.6.0 is being shipped right now, could you please try with the instructions I sent you in the previous post and tell me if that helps?

Cheers :)

**Comment by Adspectus** [comment]
I would do so but I am missing update instructions on your page. I remember I used this silly snap thing - which I do not like - to install but when I do a "snap refresh --list" I got "All snaps are uptodate", however a "snap list" shows me: 

```
espanso               0.5.5                       31    latest/stable    federicoterzi  classic
```

**Comment by federico-terzi** [comment]
> I would do so but I am missing update instructions on your page. I remember I used this silly snap thing - which I do not like - to install but when I do a "snap refresh --list" I got "All snaps are uptodate", however a "snap list" shows me:
> 
> ```
> espanso               0.5.5                       31    latest/stable    federicoterzi  classic
> ```

You are absolutely right, I forgot to release the update on snapcraft! This should be good to go now, let me know it works

Thanks for pointing that out :)

**Comment by Adspectus** [comment]
Lets test with `:espanso`:
```
Hi there!
Hi there!
Hi there!
Hi there!
Hi there!
```
Looks good!

**Comment by federico-terzi** [comment]
Great! Note that this feature is still experimental and may need some tuning. Let me know if you experience any weird behavior.

**Comment by FabianoLothor** [comment]
I'm still having this issue while using FF.

The first character of a trigger sometimes isn't replaced and sometimes espanso also leaves the second character.

**Comment by FabianoLothor** [comment]
Look, I'll just type `;hello world`:

```txt
;Hello World!
;hHello World!
;Hello World!
;heHello World!
;Hello World!
;hHello World!
;Hello World!
```

My other trigger `;hw` works fine:

```txt
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Helo World!
Hello World!
Hello World!
```

**Comment by wjdenny** [comment]
I found this issue on a search because I was having a similar issue. I'll just leave this comment in case anyone else is experiencing a similar issue even after applying the user/firefox.yml solution and perhaps their keyboard layout isn't being detected for some reason. FWIW I'm on Debian 12, Wayland, Gnome 43.

`espanso log`:
> 17:43:31 [worker(44196)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.

I was using the us alt-intl keyboard layout, and noticed in `espanso log` that it wasn't recognizing my layout and asked for it to be specified explicitly. I changed the layout to standard US and espanso notified me right away that it was detected, and it's worked perfectly since. Perhaps I could continue to use the alt-intl layout if I specified it in the configuration, but I'm not sure how to know what espanso wants me to call it; similar to ryancwalsh in the last comment on issue #953 

Edit: There's some weird behavior going on. After a reboot, it's back to partial replacements as described above. The log was also showing complaints about the keyboard layout not being specified even with the standard US layout. I'm not sure how to further troubleshoot this. Even with inject and backspace delays up over 1000, there's no change.

**Comment by notafish** [comment]
I just installed Espanso and I'm having the same issue with Thunderbird. I tired the fix with a thunderbird.yml file, and it helped to go from 80% errors to maybe 10% but I still get errors (I am up to 100 for the values for inject and backspace).

For Libre Office I have a similar problem, trigger is :br for Best regards and I constantly get:
:brBest rega

Google Chrome and Google Docs seem to have no problems.


Running Linux Mint 21.2

**Comment by daviddelven** [comment]
Is this related to the use of Espanso on Mozilla Firefox?

**Comment by smeech** [comment]
> Is this related to the use of Espanso on Mozilla Firefox?

Browser search-bars are known to be problematic, perhaps because most browsers cause delays while trying to do their own auto-complete or make suggestions, while the characters are being inserted. Fields in web-pages usually work better.
