### ISSUE TITLE
Some triggers are not recognized on non-US keyboard layouts on Windows

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#307]
For example, the `{{` trigger works when using a US keyboard layout, but not an Italian one (and judging by #305 , also the Spanish one).

**Comment by federico-terzi** [comment]
I investigated further and the problem seems more difficult to solve than it may seems.
In the Italian keyboard, to type the `{` character you need to press ALTGR. The problem is that while that key is pressed (or the ALT key) the backspace don't work.
I initially thought it could be easy to solve by injecting an ALT release event, but it doesn't work.
So for now, there is no solution to this problem. If anyone is able to solve it please let me know!

**Comment by mimmiepower** [comment]
It seems that with AutoHotKey, symbols that require you to press AltGr do not work as hotkeys (similar to Espanso). AutoHotKey does however have a way to assign hotkeys to AltGr as well as AltGr key combinations, so in that way you can work around it. It seems to me that you have to specifically inject an AltGr release event instead of a normal Alt release. Though really I am just guessing, I don't have a clue what I am talking about.

[AutoHotKey documentation on AltGr](https://www.autohotkey.com/docs/Hotkeys.htm#AltGr)

**Comment by federico-terzi** [comment]
@mimmiepower Thank you for pointing that out, I'll make sure to check if AutoHotKey can help us with this issue :)
