### ISSUE TITLE
Espanso toggles itself multiple times when keeping the toggle_key pressed

### ISSUE THREAD

**Issue by jothanne** [federico-terzi/espanso#328]
When pressing and holding the ALT key, Espanso is permanently toggling between OFF and ON. That's really a problem when you need the ALT key in combination with other keys as shortcuts in other programs.
In version 0.5.5 of Espanso everything was fine - as expected longer pressing the ALT key had no effect concerning Espanso.

**Comment by federico-terzi** [comment]
Hey @jothanne,

I'm sorry you are experiencing this issue. Indeed I had to change the ALT handling so that now it responds to key-down instead of key-up, therefore when keeping a key pressed it has this side effect.

I'll make sure to mitigate it in the upcoming releases. In the meanwhile, you could try changing the toggle key to something on the other side.
For example, I usually use my left CTRL with shortcuts and therefore I have set my toggle key to:

```
toggle_key: RIGHT_CTRL
```

Cheers :)

**Comment by mplattner** [comment]
Would be cool if this can be fixed (even for `toggle_key: RIGHT_CTRL`). Many thanks!
