### ISSUE TITLE
Espanso v0.7.0 not updating via Homebrew

### ISSUE THREAD

**Issue by jamescridland** [federico-terzi/espanso#415]
There appears to be a SHA256 mismatch on the file to download, and it won't update via Homebrew, which is a shame.

```
jamescridland@Jamess-MacBook-Pro ~ % brew update 
Already up-to-date.
jamescridland@Jamess-MacBook-Pro ~ % brew upgrade
Updating Homebrew...
==> Upgrading 1 outdated package:
federico-terzi/espanso/espanso 0.6.3 -> 0.7.0
==> Upgrading federico-terzi/espanso/espanso 0.6.3 -> 0.7.0 
==> Downloading https://github.com/federico-terzi/modulo/releases/download/v0.1.0/modulo-mac
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/280207696/3e380280-e594-11ea-81c5-62cf48edf44f?X-Amz-Algorithm=AWS4-HMAC-SHA
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 1ed432454f7b78fd0e9fd24c513bbb19ffc53e8b1b11447872671d83be2b3050
  Actual: f2009520ea5e95dde171a9b89612e2aee09f79281e07e411d8ecbbc20319e622
 Archive: /Users/jamescridland/Library/Caches/Homebrew/downloads/1e3b332721948c3bac4666e178427b6003fc2d418ce1017052c5deec80d6012e--modulo-mac
To retry an incomplete download, remove the file above.
```

**Comment by lkrms** [comment]
Rolling back to the 0.6.3 formula results in SHA256 mismatch errors too. It's difficult to see, from the relevant commit history and release files, where this discrepancy was introduced -- hopefully versioned builds of packages aren't being replaced ad-hoc?

For now, my macOS deployment scripts are broken because of this--here's hoping updated builds and/or hashes can be pushed up soon :)

**Comment by federico-terzi** [comment]
Hey guys,
I'm sorry you experienced this problem, this should be good to go now. Yesterday I pushed a little update to `modulo`, but I didn't consider that the sha256 of the espanso formula wouldn't update automatically.

Let me know if that works now (this weekend I didn't have a mac to test it out)

> Rolling back to the 0.6.3 formula results in SHA256 mismatch errors too. 

That's probably because prior to version 0.7.0 the formula pulled directly from the `latest` version of espanso, therefore it didn't offer rollback capabilities. Since the last release, I introduced explicit versioning, so from now on this problem should be fixed (I might have to introduce tags as well on the repo, but that's another story).

Sorry again guys, and thanks for your help :)

**Comment by jamescridland** [comment]
No worries, Federico - thank you. Worked a treat. Thanks.

```
jamescridland@Jamess-MacBook-Pro ~ % brew upgrade
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (federico-terzi/espanso, homebrew/core and homebrew/cask).

==> Upgrading 1 outdated package:
federico-terzi/espanso/espanso 0.6.3 -> 0.7.0
==> Upgrading federico-terzi/espanso/espanso 0.6.3 -> 0.7.0 
==> Downloading https://github.com/federico-terzi/modulo/releases/download/v0.1.
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> Downloading https://github.com/federico-terzi/espanso/releases/download/v0.7
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
🍺  /usr/local/Cellar/espanso/0.7.0: 4 files, 14MB, built in 5 seconds
Removing: /usr/local/Cellar/espanso/0.6.3... (3 files, 7.6MB)
Removing: /Users/jamescridland/Library/Caches/Homebrew/espanso--0.6.3.tar.gz... (7.6MB)
```

**Comment by federico-terzi** [comment]
@jamescridland Glad to hear that :) Closing the issue

**Comment by lkrms** [comment]
Whoops, 2 months later and I'm only just getting around to saying thank you! Sorry, my inbox/life is a bit of a disaster at the moment. Really appreciate your speedy response and fix, @federico-terzi :smiley:

**Comment by federico-terzi** [comment]
@lkrms No worries! I appreciate it :)
