### ISSUE TITLE
Multi-character replacements fail in Google Docs

### ISSUE THREAD

**Issue by bennotkin** [federico-terzi/espanso#488]
Writing a trigger for a multi-character replacement in a Google doc invariably returns a 1 to 3 letter clipping of the intended replacement.

For example, using the lorem package, `:lorem` returns _qvo_ instead of a full lorem ipsum sentence. 

The clipping seems to be consistent. My trigger `:1abc`, which should return _qwertyuiopasdfghjklzxcvbnm_, returns _qx_; my trigger `:2abc` should yield the same pattern doubled, and gives _qxg_, and finally `:3abc` returns _qxgo_. Note that espanso is giving every 20th letter: in the full pattern, _o_ is 20 chars after _g_ is 20 chars after _x_ is 20 chars after _q_.

Note that these matches work fine outside of Google Docs, even in other Google Drive applications like Sheets. I have recreated this problem in multiple documents, but have not used another account. Single-character replacements like the arrow package's `\rarrow` for → work fine.

**Comment by federico-terzi** [comment]
Hey,
What OS are you using? It might be because Google Docs is slow to process keyboard events and therefore some of them are lost.
In this case, you have 2 options:
1. Specify `backend: Clipboard` in your `default.yml` file.
2. Specify the `force_clipboard: true` option inside the matches you want to use on Google Drive. [Example](https://github.com/federico-terzi/espanso/issues/331#issuecomment-644383497).

Keep in mind that if solution 1 is working, you could also limit the backend to Clipboard only to Google Docs and not the other apps by creating an [app-specific configuration](https://espanso.org/docs/configuration/#application-specific-configurations)

Cheers :)

**Comment by bennotkin** [comment]
Amazing! Thanks for the rapid reply. Just put in the first option and everything's running great. Running macOS Catalina.

**Comment by federico-terzi** [comment]
@bennotkin Glad that solved your issue! In the future, if you find the `backend: Clipboard` limiting (for example, it overwrites non-text clipboard content after an expansion), you might want to create a Chrome/Safari only patch, so that it uses the default backend on other apps.

Cheers :)
