### ISSUE TITLE
Multi-line expansions when accentued character is present

### ISSUE THREAD

**Issue by damufo** [federico-terzi/espanso#499]
Xubuntu 20.04
Thunderbird 78.3.3
LibreOffice 6.4.6.2

```
- trigger: ":nln"
  replace: |
            exactly as you see
            will appear these three
            lines of poetry
```

add "é" character

```
- trigger: ":nla"
  replace: |
            exactly as you see é
            will appear these three
            lines of poetry
```
Thunderbird
Not worl when accentued character is present
Result Thunderbird
![espanso_multiline_accentued_character](https://user-images.githubusercontent.com/4057369/96682744-8e0b2e00-1379-11eb-886e-a5c01c1b3159.png)

Libreoffice writer
The result is the other way around, not work when no accentued character is present

Rersult LibreOffice
![espanso_multiline_accentued_character_writer](https://user-images.githubusercontent.com/4057369/96683060-f0fcc500-1379-11eb-8458-92fa34a7fb2d.png)

Any idea?

Very thanks

**Comment by federico-terzi** [comment]
Hey @damufo,

I'm sorry you experienced this problem! This is due to the different ways espanso handles special characters:
* If there are only ASCII chars, it tries to inject them directly
* If there are non-ASCII chars (like the accented letters), it uses the clipboard to paste the content.

Unfortunately, with Thunderbird the latter option requires a little patch from your side to work correctly. Please see this guide https://github.com/federico-terzi/espanso/issues/285#issuecomment-629849295

Keep in mind that the mentioned `user/` directory is inside the espanso configuration directory

Let me know if that helps, and feel free to reopen the issue if that doesn't solve your problem

Cheers :)

**Comment by damufo** [comment]
Hello! 
#285 (comment)
Work for me.
Very thanks!

**Comment by federico-terzi** [comment]
Great :)
