### ISSUE TITLE
Click buttons on webpage

### ISSUE THREAD

**Issue by reesericci** [federico-terzi/espanso#576]
I would like to be able click a button on a webpage after expanding text. Goes along with the macro support

Ex:

- Activate espanso with :xyz
- Fill in text
- Press button
- Fill in more text
<img width="472" alt="image" src="https://user-images.githubusercontent.com/19589006/106050184-92e42a00-60ac-11eb-9d71-b8675516c5d9.png">
Like here in rancher. Adding multiple annotations at once

**Comment by federico-terzi** [comment]
Hey @reesericci,

Thank you for the feedback! But how could espanso know the button position to simulate the click?

Cheers :)

**Comment by reesericci** [comment]
I don't really know, but it would be a cool feature. Something like how AutoHotKey does it?

**Comment by federico-terzi** [comment]
@reesericci The biggest problem is that once we implement a feature, we need to port it to all the supported platforms, and for this feature it might not be possible....

The only feasible solution I can see, is to "press" the button by injecting the right number of "tabs" and then an "enter", but that might not be possible.

For now, I'll close this issue as espanso is mostly focused on keyboard interactions. Feel free to add any feedback if needed :)

**Comment by CDejoEcobee** [comment]
Sorry for the necropost, but this seems like the best place to put it

I've thought that maybe it could use a browser addon, and websockets to pass data too and from the addon

I believe that would be fairly platform agnostic, and would open up some really interesting possibilities, like using CSS selectors to grab data from the page, not just enable it to press buttons.

Since there's only really 2 browsers you'd need to worry about, chromium based, and gecko, and the differences there are minor.

As for the espanso side, I would suggest having espanso handle the websocket server, and just having the browser addon connect to it, using something like [Warp](https://github.com/seanmonstar/warp/tree/master)
