### ISSUE TITLE
True portable mode not possible

### ISSUE THREAD

**Issue by alkuzad** [federico-terzi/espanso#623]
Hi

I like software a lot, seems I don't have to write my own after all with AutoIT/AutoHotKeys :) 

I installed it with scoop which should install portable version but it seems it's not possible currently to achieve that as:

Creating .espanso folder where binary is will get configuration from this folder
Creating .espanso/packages folder will keep packages repos there
Everything else goes into AppData/Local 

Is there an option to enable true portable mode ?

**Comment by federico-terzi** [comment]
Hey @alkuzad,

Thank you for the feedback! Indeed, a true portable mode is not currently possible. Given that I'm rewriting espanso from scratch in #594, I'll make sure to account for this case.

Espanso needs a temporary directory to write some cache files, would it be acceptable to write them within the executable directory? Or should that directory remain read-only?

I'm open to suggestions :)

**Comment by alkuzad** [comment]
@federico-terzi thanks for fast feedback :) As long as these files are temporary they can be in binary folder. Scoop only moves folders/files that are desired to persistent folder to keep them between updates so all cache/log files will be lost anyway. Only content of .espanso (with packages installed) will be kept.

**Comment by federico-terzi** [comment]
@alkuzad All right, thank you! I'll try to add a feature that automatically extracts those resources (log file, icons, all the ones that are currently stored into the AppData/Local) in a folder located in the same one as the binary file. So in the end, we would end up with:

```
espanso.exe
.espanso/
.espanso-cache/
```

Let me know if you have any concerns with this approach

**Comment by federico-terzi** [comment]
Hey guys,

The new alpha v2 release is now available as a portable app as well. You just need to extract the zip and then everything will be self-contained in that folder, including cache files and configurations.

I think we can safely close this issue now, but feel free to reopen if you encounter any other problems or have some feedback! :)

Cheers :)

**Comment by stewcam** [comment]
I have been testing portable mode on a Windows 11 laptop with an installed copy of Espanso 2.2.1. After exit from the installed copy I started a portable copy. However, I see that the running copy of portable Espanso does not correctly override the installed version of espanso. If I open a command prompt (even in the portable Espanso program folder) and type 'espanso path' I still see the installed Espanso paths. Also if I install a package from the hub while running portable Espanso it will install to the default installed location rather than to the portable folder .espanso\packages. To resolve this issue it is necessary to uninstall the installed copy of Espanso and then run espanso.cmd from the portable Espanso program folder.

I guess this is not a common scenario. However, it certainly confused me!

**Comment by joh6nn** [comment]
@stewcam i'm not at my desk right now, and it's been a while since I've used a portable app on Windows, but the behavior you describe matches my memory/expectations for app management on Windows:

Running `espanso` should check %PATH%, and if there's no matches it should fail, even if the current folder has an executable named `espanso` in it. To run the portable app from the cli, you need to specify the path to the app, eg `C:\Users\stewcam\espanso\espanso.exe` or cd to the right folder and run `./espanso.exe`

Can you try that and confirm if it works as expected?

**Comment by stewcam** [comment]
@joh6nn If I exit the installed copy of Espanso and then run 'START_ESPANSO.bat ' from the folder with portable Espanso (d:\temp\EspansoPortable) I get the following response from 'espanso path' with the terminal open in the portable folder:
```
Config: C:\Users\Cam\AppData\Roaming\espanso
Packages: C:\Users\Cam\AppData\Roaming\espanso\match\packages
Runtime: C:\Users\Cam\AppData\Local\espanso
```
There is no espanso.exe file in the Windows portable folder. There is espansod.exe but the readme.txt file includes a warning to avoid running it directly and recommends 'START_ESPANSO.bat'. However, if I exit portable Espanso and restart it using 'epanso.cmd start' followed by 'espanso.cmd path' I do get your expected response:
```
Config: D:\Temp\EspansoPortable\.espanso
Packages: D:\Temp\EspansoPortable\.espanso\match\packages
Runtime: D:\Temp\EspansoPortable\.espanso-runtime
```
Thanks for putting me on the right track. Although there is no bug here it would be a useful enhancement if this was more obvious.

**Comment by joh6nn** [comment]
Ok, glad you got it working. Let's see about adding a README and/or something in the docs to make this more obvious 🙂
