### ISSUE TITLE
Espanso keeps diasbling itself

### ISSUE THREAD

**Issue by G4bbix** [federico-terzi/espanso#714]
Hey there

Recently I have started using espanso on my Windows PC and I love it. It saves a lot of time. However espanso often disables itself. The log under C:\Users\User\AppData\Local\espanso\espanso.log does not show anything but that it has been disabled. 
Are there any additonal logs that I should check?
Are there any dependencies that I that might resolve this? 

Cheers G4bbix

**Comment by federico-terzi** [comment]
Hey @G4bbix,

I'm sorry you experienced this problem! Are you double pressing the ALT key? Because that's the default toggle key used to enable/disable espanso. You can find out more here (even disable it if you want): https://espanso.org/docs/configuration/#customizing-the-toggle-key

Let me know if that helps

Cheers :)

**Comment by G4bbix** [comment]
Hey @federico-terzi 
That was indeed what happend. Kudos for the quick respsonse!

Cheers G4bbix
