### ISSUE TITLE
Espanso toggles to "disabled" by itself

### ISSUE THREAD

**Issue by TwentyH** [federico-terzi/espanso#722]
Hello,
Espanso disables itself after some time without a clear reason. How can I find more information?

> 11:56:18 [ INFO] worker is running!
> 12:44:29 [ INFO] Toggled: espanso disabled
> 12:55:21 [ INFO] Toggled: espanso enabled
> 09:35:12 [ INFO] Toggled: espanso disabled
> 09:52:49 [ INFO] Toggled: espanso enabled
> 11:05:55 [ INFO] Toggled: espanso disabled
> 12:49:33 [ INFO] Toggled: espanso enabled
> 10:44:40 [ INFO] Toggled: espanso disabled
> 12:23:29 [ INFO] Toggled: espanso enabled
> 15:00:44 [ INFO] Toggled: espanso disabled
> 15:38:18 [ INFO] Toggled: espanso enabled
> 11:32:38 [ INFO] Toggled: espanso disabled
> 16:20:58 [ INFO] Toggled: espanso enabled
> 07:26:48 [ INFO] Toggled: espanso disabled
> 09:45:53 [ INFO] Toggled: espanso enabled
> 06:40:42 [ INFO] Toggled: espanso disabled
> 08:23:09 [ INFO] Toggled: espanso enabled
> 08:29:07 [ INFO] Toggled: espanso disabled
> 08:29:21 [ INFO] Toggled: espanso enabled

`

**Comment by federico-terzi** [comment]
Hey @TwentyH,

I'm sorry you experienced this problem! Are you double pressing the ALT key? Because that's the default toggle key used to enable/disable espanso. You can find out more here (even disable it if you want): https://espanso.org/docs/configuration/#customizing-the-toggle-key

Let me know if that helps! Feel free to reopen the issue if that doesn't solve your problem

Cheers :)

**Comment by TwentyH** [comment]
I forgot to reply that I disabled the toggle key, and it solved the problem: Espanso doesn’t get disabled anymore. I am not sure when or how I activated the double tap on the ALT key (or if it was somehow sent by Windows), but I don’t have the problem anymore. Thank you!

**Comment by federico-terzi** [comment]
Sounds good, thank you!
