### ISSUE TITLE
Use XDG_CONFIG_HOME for storing user configurations

### ISSUE THREAD

**Issue by ericonr** [federico-terzi/espanso#73]
Hey there!

For Linux, there's a standard that's usually followed for configuration files, which avoids filling up the user's home directory. There's usually a hierarchy of locations where these files will be searched for, which for espanso could go something like this:

* `$XDG_CONFIG_HOME/espanso`
* `$HOME/.config/espanso`
* `$HOME/.espanso`

Following this structure is great, because it allows backwards compatibility, while also making it possible for your users to easily switch the location of their config files. Ideally, the default location to create a config directory when the application can't find any existing ones would be the first one (and then the second and so forth).

How would you feel about this change? I could be interested in trying to implement it.

PS: I'm the one who commented about Wayland on reddit a few days ago! I tried out espanso, and it actually works for applications that are running inside XWayland, which is an X server inside Wayland (for applications that aren't compatible yet - or ever). For some reason `:date` was using `q` instead of  `/`, though.

**Comment by federico-terzi** [comment]
Hi,
First of all, thank you very much for the great feedback!
This change could definitely improve the Linux experience and I'm looking forward to developing the feature.
I could develop it in a few days, but if you want to give it a try I can wait. Have you ever used Rust? Otherwise, I can give you a few hints on where you should start looking up in the codebase, it should be an easy change.

PS: The issue you reported is probably due to a bug that I'm currently trying to fix. Could you please try to edit the `default.yml` file adding: 
```yaml
backend: Clipboard
``` 
as an option, then restarting espanso end see if that solve the problem of `q` instead of `/`?

**Comment by gahag** [comment]
I'm willing to have a go at this. Can I?

**Comment by federico-terzi** [comment]
Hi @gahag, 
I would wait for a response from @ericonr for a couple of days as he originally proposed this change and shown interest in implementing it. 
That said, this should be an easy feature to develop. I will create in the next few days a `contributing` page with compilation instructions, but for now, here's a short summary:

* Compilation: espanso requires rust, cmake and a c++ compiler to work ( on linux g++ is the one I'm using ).

* Every new feature should be developed in the `dev` branch, so **any pull request has to be merged in the dev branch first**. This also has the additional advantage of CI compatibility tests beforehand.

* The change should affect the `src/config/mod.rs` [get_default_config_dir](https://github.com/federico-terzi/espanso/blob/6e16a9a20bf1521c23b5218d0d8d1b5bade5bd67/src/config/mod.rs#L363) method. This method should also create the directory itself with the `create_dir_all` at this point.

**Comment by federico-terzi** [comment]
@gahag thanks again, I'll surely do! :)

**Comment by federico-terzi** [comment]
Hi guys, here's a quick update:

Many people pointed out this problem and I also received a pull request about it ( #77 ).
At the end of the day, it turned out more complex than expected, so I decided implement the solution myself using your great feedbacks.
The new espanso version ( v0.3.0 ) should be released by the end of the week with this fix, without breaking existing espanso configuration ( the current one will be deprecated though ).

Thank you for your help
