### ISSUE TITLE
Espanso doesn't work in telegram desktop

### ISSUE THREAD

**Issue by crsov** [federico-terzi/espanso#753]
OS: Fedora release 33 (Thirty Three) x86_64
Host: Vostro 3491
Kernel: 5.13.14-100.fc33.x86_64
Resolution: 1920x1080
WM: sway (xwayland)
CPU: Intel i5-1035G1 (8) @ 3.600GHz
GPU: Intel Iris Plus Graphics G1
Memory: 2218MiB / 7708MiB
espanso: 0.7.3

Espanso works in brave-browser, almost all electron apps, but doesn't work in telegram desktop. I can attach screenshots, but it makes no sense.

**Comment by federico-terzi** [comment]
Hey @crsov,

Thanks for reporting this issue! I suspect this is due to the fact you are on a Wayland system, which is not currently supported. The next version (#594, coming in the next few weeks) ships with an experimental Wayland backend, but your version (0.7.3) doesn't.
My theory is that _some_ applications are working due to the XWayland compatibility layer, which is not what Telegram Desktop uses.

So for now, you'll have to wait for version 2 or switch to an X-based desktop environment

Cheers :)
