### ISSUE TITLE
How to escape characters in config.

### ISSUE THREAD

**Issue by asimpson** [federico-terzi/espanso#76]
If I have the following config:
```
  - trigger: "\\e"
    replace: "/expand"
```
When I type `\e` the expansion is `/xpand`.

**Comment by federico-terzi** [comment]
Hi,
Thank you for reporting the problem. Which operating system are you using? 
I quickly tried it on Windows and is working as expected, I'm not experiencing the problem.
I suspect it is a platform-specific bug.

**Comment by asimpson** [comment]
Thanks for looking into it!

> Thank you for reporting the problem. Which operating system are you using?
Ubuntu 19.

> I suspect it is a platform-specific bug.
That's a bummer.

**Comment by federico-terzi** [comment]
@asimpson alright, I'll look into it in the next few days. Thanks for your feedback!

**Comment by asimpson** [comment]
Apprecaite it! Wish I knew enough Rust to provide a failing test or fix it myself.

**Comment by federico-terzi** [comment]
Turns out it happens because of a `libxdo` bug, the library I use to simulate the keyboard on Linux. Because this is one of many bugs regarding that library, I'm switching the default backend to `Clipboard` on Linux, this should solve many problems such as this one.
The only downside is that instead of simulating keystrokes it simulates a Copy/paste, so the current clipboard content gets overwritten when expanding a match.

**Comment by asimpson** [comment]
> Turns out it happens because of a `libxdo` bug, the library I use to simulate the keyboard on Linux. Because this is one of many bugs regarding that library, I'm switching the default backend to `Clipboard` on Linux, this should solve many problems such as this one.
> The only downside is that instead of simulating keystrokes it simulates a Copy/paste, so the current clipboard content gets overwritten when expanding a match.

Appreaciate it! :pray:
