### ISSUE TITLE
API to show triggers

### ISSUE THREAD

**Issue by es183923** [federico-terzi/espanso#786]
The current espanso search box is nice, but I'd like more customization over it. One way to do this is to give an API, so that it can be integrated with other search apps, and espanso won't need to have to have a lot of complex settings. Could this be possible to implement?

eg: 
```bash
espanso triggers show --all --format json
```
```json
[{
	"trigger": ":espanso",
	"replace": "Hi there!"
},
{
	"trigger": ":vscode",
	"replace": "only in TextEdit",
	"filter_class": "TextEdit"
}]
```

**Comment by federico-terzi** [comment]
Hey @es183923,

Thank you for the feedback! We are going to bring this feature back (https://github.com/federico-terzi/espanso/issues/780) in the next couple of weeks :)

Keep in mind that it's unlikely we will include "filter_class" in the output due to the way the architecture works. You will probably need to specify it as an arg, like:

```
espanso match list --filter_class "TextEdit" --format json
```

And something like the following to show all the matches

```
espanso match list --all --format json
```

Would that work for your use-case?

Cheers :)

**Comment by federico-terzi** [comment]
@es183923 Good point, my example was not very accurate, sorry!

You would use something like this:

```
espanso match list --class "TextEdit" --format json
```

Which basically can be read as "show me all the triggers that are active if the class is TextEdit". As far as I understand, that would solve your use case, right? :)

**Comment by federico-terzi** [comment]
Hey,

I'm publishing this feature in the v2.0.5-alpha release, you'll be able to run these commands:

```
espanso match list --class "TextEdit" --json

# or

espanso match list --json
```

Cheers :)

**Comment by Garulf** [comment]
How would one use this on Windows?

**Comment by skydiver** [comment]
hey @federico-terzi 

would be possible to do something like `espanso match list --class *` ?
