### ISSUE TITLE
Small (but sometimes significant) difference between 0.7.3 and 2.0.2

### ISSUE THREAD

**Issue by tmsg-gh** [federico-terzi/espanso#793]
Hi Federico... nice to see the revamp of espanso! I have installed the latest alpha (Debian/64 bit) and so far most of my stuff works as expected... so I have indeed switched to the alpha :+1:

However, there's one item that's troublesome. I have a match that looks like this:
```
  - trigger: ¬¬
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: xdotool set_desktop --relative -- -1

```
This worked well in 0.7.3. In 2.0.2 though it seems espanso **first** executes the cmd: bit (ie goes to the previous desktop) and **then** injects the two backspaces required... but of course those end up in the wrong application :-)

Additionally I am not sure whether you have had the wish and/or time to look into the issue I mentioned in #502 re word: true.

Also, how can I reconfigure the Alt-Backspace hotkey/jkj combo for the Search bar (very nice feature BTW)? I looked through the docs but haven't been lucky.

Great work and I am very much looking forward to the final release.

**Comment by federico-terzi** [comment]
> Well... whenever people are given a powerful tool they will abuse it in ways that its dev never dreamt of.. not in his worst nightmares 😅

That's right :)

> I do think that there may be quite a few use cases (for instance activating a different window before expansion etc) where executing shell command(s) before the backspacing is performed is actually creating a situation v similar to the one I found myself in. But perhaps I am misunderstanding the way this works.

Thank you for sharing your insights, I think I've got a good idea of what you mean :)
What I meant with my previous comment is that the current _text expansion_ behavior seems reasonable, as a regular expansion should be without side-effects: `you type some text in app A, it gets replaced in app A`. This seemingly arbitrary constraint is necessary to guarantee that espanso will work as expected: if you change the app in the meanwhile with a script/shell command, espanso can't guarantee that the output will be consistent.

With that being said, I absolutely understand that some users (myself included) might want to go beyond simple text replacements and gain more control, this is what the macro feature #556 will be there for :)

For example, I can see your use-case being solved with something like this:

```yaml
- trigger: ¬¬
  macro: |
    shell("xdotool set_desktop --relative -- -1")
```

In this case, the trigger text will be removed _before_ executing the macro, so that should handle your needs pretty well!

I'm happy you were able to find a working workaround in the meanwhile! :) Thanks for sharing

**Comment by federico-terzi** [comment]
> To quote Larry Wall: "Easy things should be easy, and hard things should be possible."

Love this quote! I'll probably borrow it :)

> Any idea when the macro feature will be operational? (When it's ready, eh? smile )

After the v2 is stable, I'll move to that one :) We still need to fix packages and the docs, so probably early 2022. The only thing I know is that it's likely those macros will be written in Javascript so that it has very few barriers to entry (most people can learn basic JS in a matter of minutes, if they don't know it already) by bundling the [boa](https://github.com/boa-dev/boa) engine.

> In addition to textual triggers, hotkeys (ie Ctrl-Shift-SomeKey) should be possible.

Good point, I absolutely agree with you :) In fact, the v2 comes with [hotkeys triggers](https://github.com/federico-terzi/espanso/blob/master/espanso-engine/src/event/mod.rs#L59) already, they are simply not wired up to "normal" matches. For example, the shortcut to open the search bar is a match itself, and is triggered by an hotkey :)

This one is likely to come very soon, I haven't wired it up already because it requires some more testing, but I think it will be a key ingredient when macros are implemented. I expect most macros to be triggered by either an hotkey or the search bar

> Special keys (ie Left, F10 etc) in the expansion string plus a code to create a delay between keys.

Absolutely agree, this is a highly requested feature (#286). I haven't implemented it yet because, in my mind, this feature will simply be a different "frontend" for the macro one. For example, a pseudo match like:

```
- trigger: "email"
  replace: "This is a subject<TAB><DELAY:100>This is the email message"
```

will be interpreted by Espanso as a macro:

```
- trigger: "email"
  macro: |
    type("This is a subject);
    key("tab");
    delay(100);
    type("This is the email message);
```

(this is only pseudo code, the actual syntax will vary). 
The idea is that we implement a more general mechanism first (macros), and then build a simpler frontend on top of it :)

> In forms created with modulo there's currently a Submit button. I would like to be able to add a Cancel button as well and, that's my main wish here, be able to "press" Submit with the Return/Enter key and Cancel with Escape (I am a total keyboard warrior, not a mouse fan).

Thank you for the feedback! Forms are very rough indeed, we still have a ton of work to do with them :) 
Regarding the keyboard shortcuts, you should be already able to submit the form by pressing CTRL+Enter and cancel with Escape :) See also #709 

Cheers :)

**Comment by tmsg-gh** [comment]
> cancel with Escape :)

Indeed. As there was no Cancel button I didn't even try Escape... my bad :-1: 

> In fact, the v2 comes with [hotkeys triggers](https://github.com/federico-terzi/espanso/blob/master/espanso-engine/src/event/mod.rs#L59) already, they are simply not wired up to "normal" matches. For example, the shortcut to open the search bar is a match itself, and is triggered by an hotkey :)

Yeah, I was thinking that this capability was already somewhere buried in the alpha but not yet made externally visible. V Good!
