### ISSUE TITLE
Very long-term suggestion: add Lua as espanso's fully-fledged internal script language

### ISSUE THREAD

**Issue by tmsg-gh** [federico-terzi/espanso#813]
Lua is a small (~200kb compiled) but powerful scripting language. It is written in pure ANSI C and v portable. There are already Rust bindings, see for instance https://docs.rs/crate/rlua/0.17.1 .

I have used Lua in two different scenarios to add scripting to an application and in both cases it was an easy and straightforward process.

This is not a suggestion for now or even for the next few months. It's rather an idea for a long-term addition to espanso.

**Comment by archetyped** [comment]
Long-time JS user, recent Lua learner (Hammerspoon!), and I lean toward Lua as a preferred in-app scripting language as it seems like a better fit for needs outside of a web browser (standard libraries for IO, OS-level operations, etc.).  I also don't love the idea of adopting a language primarily because of its (current) popularity.

In terms of barrier to entry...

* Programmers: Should be able to pick up Lua very quickly (e.g. [Learn Lua in Y Minutes](https://learnxinyminutes.com/docs/lua/))
* Non-Programmers: About the same learning curve (Lua or JS) to get started and do simple things.

In the end, I'll be more than happy to see *any* fully-fledged language built into Espanso :)

**Comment by federico-terzi** [comment]
@archetyped thanks for sharing your thoughts!  Those points are definitely valid :)
