### ISSUE TITLE
Allow the output of `git` commands

### ISSUE THREAD

**Issue by codysechelski** [federico-terzi/espanso#906]
**Describe the bug**
To be clear, this may not be a bug. It's quite possible that this is an `id10T` error. But since I didn't see a discussion forum here, I wasn't sure.

Let's say I am in my terminal and my current path is a local git repo. I would like to have a trigger such that when I type `:thisbranch`, espnaso will print the current branch. I figured this would be easy, I could just have it print the output of `git rev-parse --abbrev-ref HEAD`. But it is not working as expected.

**To Reproduce**

1. for a terminal
```bash
espanso edit
```

2. paste the following:
```bash
  - trigger: ":thisbranch"
    replace: "{{branchname}}"
    vars:
      - name: branchname
        type: shell
        params:
          cmd: "git rev-parse --abbrev-ref HEAD"
```

3. save and exit
4. `cd` to a directory which is a git repository
5. type `:thisbranch` 

**Expected behavior**
Espanso should replace the typed text with the current branch name

**Actual behavior**
Espanso replaced the typed test with nothing

**Screenshots**

https://user-images.githubusercontent.com/1571418/145632684-dc7d6549-f4c2-4216-aca6-0fc268d81e37.mp4

**Logs**
n/a

**Setup information**
- OS: MacOS
- Version: 0.7.3

**Comment by codysechelski** [comment]
I'm digging in a little more and I'm starting to get the idea that espanso is not aware of the current path. Is that right? I tired creating a match of type `shell` that just repaces the trigger word with `pwd`. It seems to always return `/`, regardless of the current path.

Any way around this?

**Comment by federico-terzi** [comment]
Hey @codysechelski,

> I'm digging in a little more and I'm starting to get the idea that espanso is not aware of the current path. Is that right?

Exactly, Espanso does not have any knowledge of your current terminal (otherwise, you wouldn't be able to use it across applications different than terminals :) )

The Shell commands you execute through espanso are invoked by the Espanso daemon and not by your current terminal.

If you want to use Espanso to manage your shell aliases, you could use normal matches like:

```yaml
  - trigger: ":thisbranch"
    replace: "$(git rev-parse --abbrev-ref HEAD)"
```

This way, Espanso will insert `$(git rev-parse --abbrev-ref HEAD)` in place of your trigger, which might be useful in your case

Cheers :)
