### ISSUE TITLE
Python: script not replacing trigger

### ISSUE THREAD

**Issue by ms3056** [federico-terzi/espanso#945]
**Describe the bug**
I have several scripts that use python to scrape information from the internet. These scripts worked great in 0.7.3 but in the 2.1.2 Alpha the triggers are not replaced. 

**To Reproduce**
1. Type in the trigger phrase, script runs, trigger remains and instead of the trigger being erased that last few characters of the text the python script it fetches are erased. It is like the trigger erase function is happening at the END instead of the beginning. 

**Expected behavior**
I expect the trigger to be replaced with the output from the script. 

**Screenshots**
I have attached a video. 

**Logs**
```
10:36:28 [daemon(5880)] [INFO] spawning the worker process...
10:36:28 [worker(26196)] [INFO] reading configs from: "C:\\Users\\blah\\AppData\\Roaming\\espanso"
10:36:28 [worker(26196)] [INFO] reading packages from: "C:\\Users\\blah\AppData\\Roaming\\espanso\\match\\packages"
10:36:28 [worker(26196)] [INFO] using runtime dir: "C:\\Users\\blah\\AppData\\Local\\espanso"
10:36:28 [worker(26196)] [INFO] using Win32AppInfoProvider
10:36:28 [worker(26196)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
10:36:28 [worker(26196)] [INFO] monitoring the status of the daemon process
10:36:28 [worker(26196)] [INFO] using Win32Source
10:36:28 [worker(26196)] [INFO] using Win32Injector
10:36:28 [worker(26196)] [INFO] using Win32Clipboard
```

**Setup information**
- OS: What OS are you using? Windows 10
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal) 2.1.2 Alpha

** Python Script ** - works great in 0.7.3
```py
import requests
import pyautogui

## function that gets the random quote
def get_random_quote():
    try:
        ## making the get request
        response = requests.get(
            "https://quote-garden.herokuapp.com/api/v3/quotes/random"
        )
        if response.status_code == 200:
            ## extracting the core data
            json_data = response.json()
            data = json_data["data"]
            # the quote
            pyautogui.typewrite(data[0]["quoteText"])
            pyautogui.typewrite("  -")
            pyautogui.press("*")
            # the author
            pyautogui.typewrite(data[0]["quoteAuthor"])
            pyautogui.press("*")
            pyautogui.press(["enter"])
        else:
            print("Error while getting quote")
    except:
        print("Something went wrong! Try Again!")


get_random_quote()
```

```yml
** The Espanso trigger **
# quote of the day
  - trigger: ":pq"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - "C:/Users/blah/AppData/Roaming/espanso/scripts/quote.py"
```

https://user-images.githubusercontent.com/23712700/149644061-bf18542a-fbfd-433b-a4d0-35a1d2fe1317.mp4

**Comment by federico-terzi** [comment]
Hey @ms3056,

I'm sorry you experienced this problem! Unfortunately, this is a tricky use-case to support because in your python script you are directly injecting keys with `pyautogui`, which in turn interferes with Espanso. The reason why this behavior worked in the previous version was that previously, the trigger was deleted _before_ evaluating the scripts, while in the v2 it's deleted _after_ running the scripts.

What I don't understand is why are you using `pyautogui` in this case, as if your goal is to insert some value from the script, then you can simply print it and Espanso will do the rest :) For example, if your script calls `print(data[0]["quoteText"])`, then Espanso will type it for you.

More complex use-cases will be supported in the future once macros #556 are implemented

PS: if you really, _really_, want to use `pyautogui` in the v2, you might work around the issue by dispatching the following actions in your script:
* Send N backspace presses, with N=your trigger length
* Do what you want to do
* Type an arbitrary string with length equal to your trigger

Cheers :)

**Comment by ms3056** [comment]
Thanks - I see. The main reason I am using pyautogui is a previous script I had was making enter and shift+enter command to make entries in my Logseq not taking app. 

Thanks for the explanation - at least I understand what the problem is!
