### ISSUE TITLE
Install manually on a Mac

### ISSUE THREAD

**Issue by DutchPete** [federico-terzi/espanso#99]
On the Mac installation page it says:
> The easiest way to install espanso on macOS is by using the Homebrew package manager, but you can also do it manually.

You only show how to use Homebrew, however, but not how to do it manually. Is there a .dmg file available?

**Comment by federico-terzi** [comment]
Hi @DutchPete,

Thanks for the feedback. At the moment, the situation on macOS is still a bit rough and there is no DMG package. The only officially supported way to install espanso on macOS is Homebrew for now, but I plan to invest a bit of effort to find an alternative solution. 

Is there any particular reason why you don't like using Homebrew?

Thanks

**Comment by DutchPete** [comment]
@federico-terzi : thanks for your reply. The reason I don't want to use Homebrew is that I am not familiar with it - I am new to the Mac. Moreover, I find the use of .dmg files very convenient if I compare it with the installation process in Windows and Linux.

In fact, when I read the procedure on your page to use Homebrew, it is also more long-winded than the installation with a .dmg files. What is your reason for only offering the Homebrew route: convenience at your end?

**Comment by federico-terzi** [comment]
Hi @DutchPete,
I totally understand your point. The reason is that espanso is not actually an App, but a daemon and, as such, it's not super easy to convert into a bundle.
I will definitely spend some time to investigate how to implement that solution, keep following this issue to stay updated.
Thanks for your feedback :)

**Comment by DutchPete** [comment]
@federico-terzi : OK, thanks I'll follow it.

**Comment by DutchPete** [comment]
@federico-terzi: in case you had not noticed, I bit the bullet and installed Homebrew - no problems encountered - then Espanso, also without problems. Did that yesterday.
It seems to be a good app, and you are a pleasant person to work with ;-) Many thanks.

**Comment by federico-terzi** [comment]
Hi @DutchPete,
Thank you for the kind words! I'm glad you liked it. 
Actually I've been researching for a while on this topic, and it seems like Homebrew will still be the recommended way still for some time because with macOS Catalina is becoming more and more difficult to distribute apps.

Thanks for your help
